# DO NOT PUT REAL VALUES IN THIS FILE

SECRET_KEY = ''

AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
AWS_STORAGE_BUCKET_NAME = ''

DOCUMENTCLOUD_USERNAME = ''
DOCUMENTCLOUD_PASS = ''

DOCUMENTS_PATH = '/'

AKISMET_API_KEY = ''

TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
FACEBOOK_APP_ID = ''
FACEBOOK_API_SECRET = ''