import os

SECRET_KEY = os.environ['SECRET_KEY']

AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']

DOCUMENTCLOUD_USERNAME = os.environ['DOCUMENTCLOUD_USERNAME']
DOCUMENTCLOUD_PASS = os.environ['DOCUMENTCLOUD_PASS']

DOCUMENTS_PATH = os.environ['DOCUMENTS_PATH']

AKISMET_API_KEY = os.environ['AKISMET_API_KEY']

TWITTER_CONSUMER_KEY = os.environ['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET = os.environ['TWITTER_CONSUMER_SECRET']

FACEBOOK_APP_ID = os.environ['FACEBOOK_APP_ID']
FACEBOOK_API_SECRET = os.environ['FACEBOOK_API_SECRET']

try:
    SENTRY_DSN = os.environ['SENTRY_DSN']
except KeyError, exp:
    print "no value for sentry_dsn, who knows what will happen"

FACEBOOK_PAGE = ''
TWITTER_USERNAME = 'globaleyewitnes'
PINTEREST_PAGE = ''
GOOGLE_UA_ID = 'UA-30635036-1'